engines:
  eslint:
    enabled: true
    checks:
      import/no-unresolved:
        enabled: false
      import/extensions:
        enabled: false
    config:
      extensions:
      - .js
      - .jsx

ratings:
   paths:
   - "**.js"
   - "**.jsx"