language: node_js
node_js:
  - "7"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

script:
  - cd client
  - npm run lint && yarn && npm run build:server
  - cd ..
  - cd server
  - npm run lint