language: node_js
node_js:
  - "7"

sudo:
  required

env:
  - CXX=g++-4.8

cache:
  yarn: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update && sudo apt-get install yarn

install:
  - cd client
  - yarn
  - cd ..
  - cd server
  - yarn

before_script:
  - cd client
  - npm run lint
  - cd ..
  - cd server
  - npm run lint

script:
  - cd client
  - npm run build:server