language: node_js
node_js:
  - "7"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

script:
  - cd client 
  - npm install && npm run lint && NODE_ENV=production webpack -p --config webpack.prod.config.js
  - cd ..
  - cd server
  - npm install && npm run lint