language: node_js
node_js:
  - "7"

sudo:
  required

cache:
  yarn: true

before_install:
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update && sudo apt-get install yarn

install:
  - cd client
  - yarn
  - cd ..
  - cd server
  - yarn add babel-eslint eslint eslint-config-airbnb-base eslint-plugin-import
  - cd ..

before_script:
  - cd client
  - npm run lint
  - cd ..
  - cd server
  - npm run lint
  - cd ..

script:
  - cd client
  - npm run build:server