language: node_js
node_js:
  - "7"

env:
  - CXX=g++-4.8
  - TEST_DIR=client
  - TEST_DIR=server

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

script: cd $TEST_DIR && npm install && npm lint