language: node_js
node_js:
  - "7"

env:
  - CXX=g++-4.8

cache:
  yarn: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before-script:
  - cd client
  - yarn
  - cd ..
  - cd server
  - yarn

script:
  - cd client
  - npm run lint && npm run build:server
  - cd ..
  - cd server
  - npm run lint