language: node_js
node_js:
  - "7"
env:
  - CXX=g++-6.2
  - TEST_DIR=client
  - TEST_DIR=server
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6.2
script: cd $TEST_DIR && npm install && npm lint